name: Build Android

on: pull_request

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v2 # Use actions/setup-java@v1 instead of v3 for compatibility
        with:
          java-version: 18 # Use 1.8 instead of '8' for compatibility
          distribution: 'zulu'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x gradlew

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build APK
        run: ./gradlew assembleDebug
