name: Build Android

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: action/setup-java@v2
        with:
          java-version: 1.8

      - name: Build Project
        run: ./gradlew assemble


